services:
  presentation-application:
    container_name: presentation-application
    image: presentation-application
    restart: unless-stopped
    build:
      context: ./application/
      dockerfile: Dockerfile
    ports:
      - "80:80"

  automation-server:
    container_name: automation-server
    image: automation-server
    restart: unless-stopped
    build:
      context: ./automation-server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ~/.kube/config:/root/.kube/config:ro
    environment:
      - KUBECONFIG=/root/.kube/config

  cluster-mcp:
    container_name: cluster-mcp
    image: cluster-mcp
    restart: unless-stopped
    build:
      context: ./cluster-mcp/
      dockerfile: Dockerfile
    volumes:
      - ~/.kube/config:/root/.kube/config:ro
    environment:
      - KUBECONFIG=/root/.kube/config
    stdin_open: true
    tty: true