services:
  presentation-application:
    container_name: presentation-application
    image: presentation-application
    restart: unless-stopped
    build:
      context: ./application/
      dockerfile: Dockerfile
    ports:
      - "80:80"