apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-mcp
  namespace: cluster-mcp
  labels:
    app: cluster-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-mcp
  template:
    metadata:
      labels:
        app: cluster-mcp
    spec:
      serviceAccountName: cluster-mcp
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: cluster-mcp
        image: ghcr.io/artificed/astdev-presentation/cluster-mcp:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /cluster-mcp/health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /cluster-mcp//health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"