---
- name: Create application directory
  hosts: all
  become: true
  vars:
    app_directory: /application

  tasks:
    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user | default('root') }}"
        group: "{{ ansible_user | default('root') }}"
