---
- name: Setup VM
  hosts: all
  become: true
  
  vars:
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
  
  roles:
    - prerequisites
    - k3s
    - github_cli
    - github_actions_runner
    - helm
    - n8n