---
- name: Setup VM
  hosts: all
  become: true
  
  vars:
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
  
  roles:
    - prerequisites
    - docker
    - app_directory
    - github_cli
    - github_actions_runner