apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentation-application
  namespace: astdev-presentation
  labels:
    app: presentation-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: presentation-application
  template:
    metadata:
      labels:
        app: presentation-application
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: application
        image: ghcr.io/artificed/astdev-presentation/presentation-application:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5678
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 5
          periodSeconds: 5
