apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: presentation-frontend
  namespace: astdev-presentation
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: presentation-frontend
            port:
              number: 80
