apiVersion: v1
kind: Service
metadata:
  name: presentation-application
  namespace: astdev-presentation
  labels:
    app: presentation-application
spec:
  type: ClusterIP
  selector:
    app: presentation-application
  ports:
  - port: 5678
    targetPort: 5678
    protocol: TCP
    name: http
