apiVersion: v1
kind: Service
metadata:
  name: automation-server
  namespace: automation-server
  labels:
    app: automation-server
spec:
  type: ClusterIP
  selector:
    app: automation-server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
