image:
  repository: n8nio/n8n
  tag: ""
  pullPolicy: IfNotPresent

encryptionKey: "4f269b9c8a271296a0f11bc47a04a177415e91a4c143c752fa44bfe63036cd3a"

service:
  enabled: true
  type: NodePort
  port: 5678

ingress:
  enabled: false

main:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  livenessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /health
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

  persistence:
    enabled: true
    size: 8Gi
    accessMode: ReadWriteOnce

  extraEnvVars:
    N8N_SECURE_COOKIE: "false"
    DB_SQLITE_POOL_SIZE: "3"
    N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
    N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"

db:
  type: sqlite
  sqlite:
    database: database.sqlite

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false

podSecurityContext:
  fsGroup: 1000